nexus:
  container_name: nexus
  build: ./nexus
  ports:
    - "8081:8081"

jenkins:
  container_name: jenkins
  build: ./jenkins
  ports:
    - "8080:8080"
  # links:
  #   - nexus:nexus
  #   - sonar:sonar
  #   - selhub:hub

db:
  container_name: db
  image: postgres
  environment:
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar

sonar:
  container_name: sonar
  build: ./sonar
  ports:
   - "9000:9000"
   - "5432:5432"

sonar-runner:
  container_name: sonar-runner
  build: ./sonar-runner
  environment:
   - SONAR_USER_HOME=/data/.sonar-cache
   - SONAR_HOST_URL=http://sonar:9000
   - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
   - SONAR_JDBC_USERNAME=sonar
   - SONAR_JDBC_PASSWORD=sonar

# selhub:
#   container_name: selhub
#   image: selenium/hub
#   ports:
#     - "4444:4444"

# nodeff:
#   container_name: nodeff
#   image: selenium/node-firefox-debug
#   ports:
#     - "5900"
#   # links:
#   #   - selhub:hub

# nodechrome:
#   container_name: nodechrome
#   image: selenium/node-chrome-debug
#   ports:
#     - "5900"
#   # links:
#   #   - selhub:hub

# postgresql:
#  image: sameersbn/postgresql:9.4-3
#  environment:
#    - DB_USER=gitlab
#    - DB_PASS=password
#    - DB_NAME=gitlabhq_production
#  volumes:
#    - /srv/docker/gitlab/postgresql:/var/lib/postgresql
#gitlab:
#  image: sameersbn/gitlab:8.0.3
#  links:
#    - redis:redisio
#    - postgresql:postgresql
#  ports:
#    - "10080:80"
#    - "10022:22"
#  environment:
#    - TZ=Europe/Berlin
#    - GITLAB_TIMEZONE=Berlin
#
#    - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string
#
#    - GITLAB_HOST=localhost
#    - GITLAB_PORT=10080
#    - GITLAB_SSH_PORT=10022
#
#    - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
#    - GITLAB_NOTIFY_PUSHER=false
#
#    - GITLAB_EMAIL=notifications@example.com
#    - GITLAB_EMAIL_REPLY_TO=noreply@example.com
#    - GITLAB_INCOMING_EMAIL_ADDRESS=reply@example.com
#
#    - GITLAB_BACKUPS=daily
#    - GITLAB_BACKUP_TIME=01:00
#
#    - SMTP_ENABLED=false
#    - SMTP_DOMAIN=www.example.com
#    - SMTP_HOST=smtp.gmail.com
#    - SMTP_PORT=587
#    - SMTP_USER=mailer@example.com
#    - SMTP_PASS=password
#    - SMTP_STARTTLS=true
#    - SMTP_AUTHENTICATION=login
#
#    - IMAP_ENABLED=false
#    - IMAP_HOST=imap.gmail.com
#    - IMAP_PORT=993
#    - IMAP_USER=mailer@example.com
#    - IMAP_PASS=password
#    - IMAP_SSL=true
#    - IMAP_STARTTLS=false
#  volumes:
#    - /srv/docker/gitlab/gitlab:/home/git/data
#redis:
#  image: sameersbn/redis:latest
#  volumes:
#    - /srv/docker/gitlab/redis:/var/lib/redis
